# for server setup(debug)
serverSetup:
  listen_port: 5000
  proxy_port: 3000

# gulpfile
gulpfile:
  is_debug: false
  obfuscator: false
  
#bitly
bitly:
  acc_token: "c72064c324947645ff111c4aab510176af0326ea"